# Generated by Django 6.0.7 on 2026-08-04 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Linear Algebra & Field Theory Explorer', max_length=200)),
                ('hero_subtitle', models.TextField(default='Interactive step-by-step LaTeX matrix solvers, 3D vector graphics, dynamic matrix resizers, Light/Dark theme toggle, LaTeX formula copy, and live Python code inspection.')),
                ('curriculum_badge', models.CharField(default='DATA SCIENCE MATHEMATICS CURRICULUM', max_length=100)),
                ('show_code_inspector', models.BooleanField(default=True, help_text='Toggle live Python code inspection tabs across all solver pages')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TopicModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Unique URL identifier e.g. gaussian, gf2, vectors', unique=True)),
                ('topic_code', models.CharField(default='TOPIC 1.1', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('unit', models.CharField(choices=[('UNIT 1', 'Unit 1: Linear Systems, Fields & Vectors'), ('UNIT 2', 'Unit 2: Inner Products, Determinants & Diagonalization')], default='UNIT 1', max_length=20)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='bi-grid-3x3', help_text='Bootstrap icon class e.g. bi-grid-3x3, bi-shield-check', max_length=50)),
                ('icon_color_class', models.CharField(default='text-info', help_text='Color class e.g. text-info, text-warning, text-success', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Topic Module',
                'verbose_name_plural': 'Topic Modules',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SavedPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('matrix_data', models.TextField(help_text='Matrix values formatted as space/newline separated text')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='linear_algebra.topicmodule')),
            ],
        ),
    ]
