# Generated by Django 6.0.7 on 2026-08-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear_algebra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='show_code_inspector',
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_subtitle',
            field=models.TextField(default='Interactive step-by-step LaTeX matrix solvers, 3D vector graphics, dynamic matrix resizers, Light/Dark theme toggle, and LaTeX formula copy.'),
        ),
    ]
