# Generated by Django 6.0.7 on 2026-08-05 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linear_algebra', '0002_remove_sitesetting_show_code_inspector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_slug', models.CharField(max_length=50)),
                ('topic_title', models.CharField(max_length=150)),
                ('input_summary', models.TextField()),
                ('result_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Calculation History',
                'verbose_name_plural': 'User Calculation Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
